<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="GSN" nsURI="http://www.goalstructuringnotation.info/1.0" nsPrefix="gsn">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eSubpackages name="Commons" nsURI="http://www.goalstructuringnotation.info/1.0/commons"
      nsPrefix="GSN_Commons">
    <eClassifiers xsi:type="ecore:EClass" name="SACMElement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="#//Commons/SACMElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//Commons/Description"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inplementationConstraint"
          upperBound="-1" eType="#//Commons/ImplementationConstraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="note" upperBound="-1"
          eType="#//Commons/Note" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValue" upperBound="-1"
          eType="#//Commons/TaggedValue" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uninstantiated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UtilityElement" abstract="true" eSuperTypes="#//Commons/SACMElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//Terminology/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImplementationConstraint" abstract="true"
        eSuperTypes="#//Commons/UtilityElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Description" abstract="true" eSuperTypes="#//Commons/UtilityElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Note" abstract="true" eSuperTypes="#//Commons/UtilityElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="TaggedValue" abstract="true" eSuperTypes="#//Commons/UtilityElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//Terminology/Expression"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Packages" nsURI="http://www.goalstructuringnotation.info/1.0/packages"
      nsPrefix="GSN_Packages">
    <eClassifiers xsi:type="ecore:EClass" name="AssuranceCasePackage" abstract="true"
        eSuperTypes="#//Artefact/ArtefactElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="assuranceCasePackageCitation"
          upperBound="-1" eType="#//Packages/AssuranceCasePackageCitation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assuranceCasePackage"
          upperBound="-1" eType="#//Packages/AssuranceCasePackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
          eType="#//Packages/AssuranceCasePackageInterface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="argumentPackage" upperBound="-1"
          eType="#//Argumentation/ArgumentPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactPackage" upperBound="-1"
          eType="#//Artefact/ArtefactPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="terminologyPackage" upperBound="-1"
          eType="#//Terminology/TerminologyPackage" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssuranceCasePackageInterface" abstract="true"
        eSuperTypes="#//Packages/AssuranceCasePackage"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssuranceCasePackageCitation" abstract="true"
        eSuperTypes="#//Packages/AssuranceCasePackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedPackage" lowerBound="1"
          eType="#//Packages/AssuranceCasePackage"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Terminology" nsURI="http://www.goalstructuringnotation.info/1.0/terminology"
      nsPrefix="GSN_Terminology">
    <eClassifiers xsi:type="ecore:EClass" name="TerminologyElement" abstract="true"
        eSuperTypes="#//Commons/ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="TerminologyPackage" abstract="true"
        eSuperTypes="#//Terminology/TerminologyElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="terminologyAsset" upperBound="-1"
          eType="#//Terminology/TerminologyAsset" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="terminologyPackage" upperBound="-1"
          eType="#//Terminology/TerminologyPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="terminologyPackageCitation"
          upperBound="-1" eType="#//Terminology/TerminologyPackageCitation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TerminologyPackageCitation" abstract="true"
        eSuperTypes="#//Terminology/TerminologyPackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedPackage" eType="#//Terminology/TerminologyPackage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TerminologyAsset" abstract="true"
        eSuperTypes="#//Terminology/TerminologyElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Category" abstract="true" eSuperTypes="#//Terminology/TerminologyAsset"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExpressionElement" abstract="true"
        eSuperTypes="#//Terminology/TerminologyAsset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="category" upperBound="-1"
          eType="#//Terminology/Category"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//Terminology/ExpressionElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
          eType="#//Terminology/ExpressionElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Term" abstract="true" eSuperTypes="#//Terminology/ExpressionElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Commons/ModelElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//Terminology/Term"/>
    <eClassifiers xsi:type="ecore:EClass" name="TerminologyAssetCitation" abstract="true"
        eSuperTypes="#//Terminology/ExpressionElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedElement" lowerBound="1"
          eType="#//Terminology/TerminologyAsset"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Argumentation" nsURI="http://www.goalstructuringnotation.info/1.0/argumentation"
      nsPrefix="GSN_Argumentation">
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentationElement" abstract="true"
        eSuperTypes="#//Commons/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentPackage" abstract="true" eSuperTypes="#//Argumentation/ArgumentationElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="argumentAsset" upperBound="-1"
          eType="#//Argumentation/ArgumentAsset" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="argumentPackage" upperBound="-1"
          eType="#//Argumentation/ArgumentPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
          eType="#//Argumentation/ArgumentPackageInterface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="argumentPackageCitation"
          upperBound="-1" eType="#//Argumentation/ArgumentPackageCitation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//Argumentation/ArgumentPackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="module" upperBound="-1"
          eType="#//Argumentation/Module" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentPackageCitation" abstract="true"
        eSuperTypes="#//Argumentation/ArgumentPackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedPackage" lowerBound="1"
          eType="#//Argumentation/ArgumentPackage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentPackageBinding" abstract="true"
        eSuperTypes="#//Argumentation/ArgumentPackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="participantPackage" lowerBound="2"
          upperBound="-1" eType="#//Argumentation/ArgumentPackage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Contract" eSuperTypes="#//Argumentation/ArgumentPackageBinding"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentPackageInterface" abstract="true"
        eSuperTypes="#//Argumentation/ArgumentPackage"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentAsset" abstract="true" eSuperTypes="#//Argumentation/ArgumentationElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Assertion" abstract="true" eSuperTypes="#//Argumentation/ArgumentAsset"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactElementCitation" abstract="true"
        eSuperTypes="#//Argumentation/ArgumentAsset">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedArtefact" eType="#//Artefact/ArtefactElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Solution" eSuperTypes="#//Argumentation/ArtefactElementCitation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPublic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentAssetCitation" abstract="true"
        eSuperTypes="#//Argumentation/ArgumentAsset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedAsset" lowerBound="1"
          eType="#//Argumentation/ArgumentAsset"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AwayGoal" eSuperTypes="#//Argumentation/ArgumentAssetCitation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="awayGoal" eType="#//Argumentation/Goal"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="moduleIdentifier" eType="#//Argumentation/Module"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AwaySolution" eSuperTypes="#//Argumentation/ArgumentAssetCitation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="awaySolution" eType="#//Argumentation/Solution"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="moduleIdentifier" eType="#//Argumentation/Module"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AwayContext" eSuperTypes="#//Argumentation/ArgumentAssetCitation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="awayContext" eType="#//Argumentation/Context"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="moduleIdentifier" eType="#//Argumentation/Module"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Claim" abstract="true" eSuperTypes="#//Argumentation/Assertion">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="assumed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="toBeSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//Argumentation/Claim">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPublic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="undeveloped" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="toBeSupportedByContract"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Justification" eSuperTypes="#//Argumentation/Claim"/>
    <eClassifiers xsi:type="ecore:EClass" name="Assumption" eSuperTypes="#//Argumentation/Claim"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentReasoning" abstract="true"
        eSuperTypes="#//Argumentation/ArgumentAsset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="structure" eType="#//Argumentation/ArgumentPackage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Strategy" eSuperTypes="#//Argumentation/ArgumentReasoning">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="undeveloped" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//Argumentation/ArgumentAsset">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPublic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="refersToExternalMaterial"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssertedRelationship" abstract="true"
        eSuperTypes="#//Argumentation/Assertion">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
          eType="#//Argumentation/ArgumentAsset"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
          eType="#//Argumentation/ArgumentAsset"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="requires" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
          defaultValueLiteral="-1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssertedInference" abstract="true"
        eSuperTypes="#//Argumentation/AssertedRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="SupportedBy" eSuperTypes="#//Argumentation/AssertedRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssertedEvidence" abstract="true"
        eSuperTypes="#//Argumentation/AssertedRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssertedChallenge" abstract="true"
        eSuperTypes="#//Argumentation/AssertedRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssertedCounterEvidence" abstract="true"
        eSuperTypes="#//Argumentation/AssertedRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssertedContext" abstract="true" eSuperTypes="#//Argumentation/AssertedRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="InContextOf" eSuperTypes="#//Argumentation/AssertedContext"/>
  </eSubpackages>
  <eSubpackages name="Artefact" nsURI="http://www.goalstructuringnotation.info/1.0/artefact"
      nsPrefix="GSN_Artefact">
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactElement" abstract="true" eSuperTypes="#//Commons/ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactPackage" abstract="true" eSuperTypes="#//Artefact/ArtefactElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactPackageCitation"
          upperBound="-1" eType="#//Artefact/ArtefactPackageCitation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactAsset" upperBound="-1"
          eType="#//Artefact/ArtefactAsset" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactPackage" upperBound="-1"
          eType="#//Artefact/ArtefactPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
          eType="#//Artefact/ArtefactPackageInterface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactPackageCitation" abstract="true"
        eSuperTypes="#//Artefact/ArtefactPackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedPackage" lowerBound="1"
          eType="#//Artefact/ArtefactPackage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactPackageBinding" abstract="true"
        eSuperTypes="#//Artefact/ArtefactPackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="participantpackage" lowerBound="2"
          upperBound="-1" eType="#//Artefact/ArtefactPackage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactPackageInterface" abstract="true"
        eSuperTypes="#//Artefact/ArtefactPackage"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactAsset" abstract="true" eSuperTypes="#//Artefact/ArtefactElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactAssetCitation" abstract="true"
        eSuperTypes="#//Artefact/ArtefactAsset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedAsset" lowerBound="1"
          eType="#//Artefact/ArtefactAsset"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Artefact" abstract="true" eSuperTypes="#//Artefact/ArtefactAsset">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactProperty" upperBound="-1"
          eType="#//Artefact/ArtefactProperty" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactEvent" upperBound="-1"
          eType="#//Artefact/ArtefactEvent" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactProperty" abstract="true"
        eSuperTypes="#//Artefact/ArtefactAsset"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactEvent" abstract="true" eSuperTypes="#//Artefact/ArtefactAsset">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Resource" abstract="true" eSuperTypes="#//Artefact/ArtefactAsset">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true" eSuperTypes="#//Artefact/ArtefactAsset">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Technique" abstract="true" eSuperTypes="#//Artefact/ArtefactAsset"/>
    <eClassifiers xsi:type="ecore:EClass" name="Participant" abstract="true" eSuperTypes="#//Artefact/ArtefactAsset"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactAssetRelationship" abstract="true"
        eSuperTypes="#//Artefact/ArtefactAsset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
          eType="#//Artefact/ArtefactAsset"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
          eType="#//Artefact/ArtefactAsset"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactRelationship" abstract="true"
        eSuperTypes="#//Artefact/ArtefactAssetRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityRelationship" abstract="true"
        eSuperTypes="#//Artefact/ArtefactAssetRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactActivityRelationship" abstract="true"
        eSuperTypes="#//Artefact/ArtefactAssetRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactTechniqueRelationship" abstract="true"
        eSuperTypes="#//Artefact/ArtefactAssetRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParticipantRoleRelationship" abstract="true"
        eSuperTypes="#//Artefact/ArtefactAssetRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactResourceRelationship" abstract="true"
        eSuperTypes="#//Artefact/ArtefactAssetRelationship"/>
  </eSubpackages>
</ecore:EPackage>
