<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SACM" nsURI="http://www.omg.org/spec/SACM/2.0" nsPrefix="sacm">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eSubpackages name="Commons" nsURI="http://www.omg.org/spec/SACM/2.0/Commons" nsPrefix="SACM_Commons">
    <eClassifiers xsi:type="ecore:EClass" name="SACMElement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="#//Commons/SACMElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//Commons/Description"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inplementationConstraint"
          upperBound="-1" eType="#//Commons/ImplementationConstraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="note" upperBound="-1"
          eType="#//Commons/Note" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValue" upperBound="-1"
          eType="#//Commons/TaggedValue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UtilityElement" abstract="true" eSuperTypes="#//Commons/SACMElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//Terminology/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImplementationConstraint" eSuperTypes="#//Commons/UtilityElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Description" eSuperTypes="#//Commons/UtilityElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="#//Commons/UtilityElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="TaggedValue" eSuperTypes="#//Commons/UtilityElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//Terminology/Expression"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Packages" nsURI="http://www.omg.org/spec/SACM/2.0/Packages"
      nsPrefix="SACM_Packages">
    <eClassifiers xsi:type="ecore:EClass" name="AssuranceCasePackage" eSuperTypes="#//Artefact/ArtefactElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="assuranceCasePackageCitation"
          upperBound="-1" eType="#//Packages/AssuranceCasePackageCitation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assuranceCasePackage"
          upperBound="-1" eType="#//Packages/AssuranceCasePackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
          eType="#//Packages/AssuranceCasePackageInterface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="argumentPackage" upperBound="-1"
          eType="#//Argumentation/ArgumentPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactPackage" upperBound="-1"
          eType="#//Artefact/ArtefactPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="terminologyPackage" upperBound="-1"
          eType="#//Terminology/TerminologyPackage" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssuranceCasePackageInterface" eSuperTypes="#//Packages/AssuranceCasePackage"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssuranceCasePackageCitation" eSuperTypes="#//Packages/AssuranceCasePackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedPackage" lowerBound="1"
          eType="#//Packages/AssuranceCasePackage"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Terminology" nsURI="http://www.omg.org/spec/SACM/2.0/Terminology"
      nsPrefix="SACM_Terminology">
    <eClassifiers xsi:type="ecore:EClass" name="TerminologyElement" abstract="true"
        eSuperTypes="#//Commons/ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="TerminologyPackage" eSuperTypes="#//Terminology/TerminologyElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="terminologyAsset" upperBound="-1"
          eType="#//Terminology/TerminologyAsset" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="terminologyPackage" upperBound="-1"
          eType="#//Terminology/TerminologyPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="terminologyPackageCitation"
          upperBound="-1" eType="#//Terminology/TerminologyPackageCitation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TerminologyPackageCitation" eSuperTypes="#//Terminology/TerminologyPackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedPackage" eType="#//Terminology/TerminologyPackage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TerminologyAsset" abstract="true"
        eSuperTypes="#//Terminology/TerminologyElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Category" eSuperTypes="#//Terminology/TerminologyAsset"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExpressionElement" abstract="true"
        eSuperTypes="#//Terminology/TerminologyAsset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="category" upperBound="-1"
          eType="#//Terminology/Category"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//Terminology/ExpressionElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
          eType="#//Terminology/ExpressionElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Term" eSuperTypes="#//Terminology/ExpressionElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Commons/ModelElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TerminologyAssetCitation" eSuperTypes="#//Terminology/ExpressionElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedElement" lowerBound="1"
          eType="#//Terminology/TerminologyAsset"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Argumentation" nsURI="http://www.omg.org/spec/SACM/2.0/Argumentation"
      nsPrefix="SACM_Argumentation">
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentationElement" abstract="true"
        eSuperTypes="#//Commons/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentPackage" eSuperTypes="#//Argumentation/ArgumentationElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="argumentAsset" upperBound="-1"
          eType="#//Argumentation/ArgumentAsset" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="argumentPackage" upperBound="-1"
          eType="#//Argumentation/ArgumentPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
          eType="#//Argumentation/ArgumentPackageInterface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="argumentPackageCitation"
          upperBound="-1" eType="#//Argumentation/ArgumentPackageCitation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentPackageCitation" eSuperTypes="#//Argumentation/ArgumentPackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedPackage" lowerBound="1"
          eType="#//Argumentation/ArgumentPackage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentPackageBinding" eSuperTypes="#//Argumentation/ArgumentPackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="participantPackage" lowerBound="2"
          upperBound="-1" eType="#//Argumentation/ArgumentPackage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentPackageInterface" eSuperTypes="#//Argumentation/ArgumentPackage"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentAsset" abstract="true" eSuperTypes="#//Argumentation/ArgumentationElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Assertion" abstract="true" eSuperTypes="#//Argumentation/ArgumentAsset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="metaClaim" upperBound="-1"
          eType="#//Argumentation/Claim" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactElementCitation" eSuperTypes="#//Argumentation/ArgumentAsset">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedArtefact" eType="#//Artefact/ArtefactElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentAssetCitation" eSuperTypes="#//Argumentation/ArgumentAsset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedAsset" lowerBound="1"
          eType="#//Argumentation/ArgumentAsset"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Claim" eSuperTypes="#//Argumentation/Assertion">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="assumed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="toBeSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArgumentReasoning" eSuperTypes="#//Argumentation/ArgumentAsset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="structure" eType="#//Argumentation/ArgumentPackage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssertedRelationship" abstract="true"
        eSuperTypes="#//Argumentation/Assertion">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
          eType="#//Argumentation/ArgumentAsset"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
          eType="#//Argumentation/ArgumentAsset"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reasoning" eType="#//Argumentation/ArgumentReasoning"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssertedInference" eSuperTypes="#//Argumentation/AssertedRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssertedEvidence" eSuperTypes="#//Argumentation/AssertedRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssertedChallenge" eSuperTypes="#//Argumentation/AssertedRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssertedCounterEvidence" eSuperTypes="#//Argumentation/AssertedRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssertedContext" eSuperTypes="#//Argumentation/AssertedRelationship"/>
  </eSubpackages>
  <eSubpackages name="Artefact" nsURI="http://www.omg.org/spec/SACM/2.0/Artefact"
      nsPrefix="SACM_Artefact">
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactElement" abstract="true" eSuperTypes="#//Commons/ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactPackage" eSuperTypes="#//Artefact/ArtefactElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactPackageCitation"
          upperBound="-1" eType="#//Artefact/ArtefactPackageCitation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactAsset" upperBound="-1"
          eType="#//Artefact/ArtefactAsset" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactPackage" upperBound="-1"
          eType="#//Artefact/ArtefactPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
          eType="#//Artefact/ArtefactPackageInterface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactPackageCitation" eSuperTypes="#//Artefact/ArtefactPackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedPackage" lowerBound="1"
          eType="#//Artefact/ArtefactPackage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactPackageBinding" eSuperTypes="#//Artefact/ArtefactPackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="participantpackage" lowerBound="2"
          upperBound="-1" eType="#//Artefact/ArtefactPackage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactPackageInterface" eSuperTypes="#//Artefact/ArtefactPackage"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactAsset" abstract="true" eSuperTypes="#//Artefact/ArtefactElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactAssetCitation" eSuperTypes="#//Artefact/ArtefactAsset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="citedAsset" lowerBound="1"
          eType="#//Artefact/ArtefactAsset"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Artefact" eSuperTypes="#//Artefact/ArtefactAsset">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactProperty" upperBound="-1"
          eType="#//Artefact/ArtefactProperty" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactEvent" upperBound="-1"
          eType="#//Artefact/ArtefactEvent" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactProperty" eSuperTypes="#//Artefact/ArtefactAsset"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactEvent" eSuperTypes="#//Artefact/ArtefactAsset">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//Artefact/ArtefactAsset">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//Artefact/ArtefactAsset">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Technique" eSuperTypes="#//Artefact/ArtefactAsset"/>
    <eClassifiers xsi:type="ecore:EClass" name="Participant" eSuperTypes="#//Artefact/ArtefactAsset"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactAssetRelationship" abstract="true"
        eSuperTypes="#//Artefact/ArtefactAsset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
          eType="#//Artefact/ArtefactAsset"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
          eType="#//Artefact/ArtefactAsset"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactRelationship" eSuperTypes="#//Artefact/ArtefactAssetRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityRelationship" eSuperTypes="#//Artefact/ArtefactAssetRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactActivityRelationship" eSuperTypes="#//Artefact/ArtefactAssetRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactTechniqueRelationship" eSuperTypes="#//Artefact/ArtefactAssetRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParticipantRoleRelationship" eSuperTypes="#//Artefact/ArtefactAssetRelationship"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactResourceRelationship" eSuperTypes="#//Artefact/ArtefactAssetRelationship"/>
  </eSubpackages>
</ecore:EPackage>
